package controlador;

import modelo.Profesor;
import persistencia.JsonDataManager;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.Scanner;
import java.util.InputMismatchException;
import java.util.Comparator; // For sorting

public class ProfesorControlador {
    private List<Profesor> profesores;
    private final JsonDataManager dataManager;
    private final Scanner scanner; // To receive input from the view layer

    public ProfesorControlador(JsonDataManager dataManager, Scanner scanner) {
        this.dataManager = dataManager;
        this.profesores = dataManager.cargarProfesores();
        this.scanner = scanner;
    }

    public List<Profesor> getProfesores() {
        return new ArrayList<>(profesores); // Return a copy to prevent external modification
    }

    public Optional<Profesor> getProfesorPorId(String id) {
        return profesores.stream().filter(p -> p.getId().equalsIgnoreCase(id)).findFirst();
    }

    public Optional<Profesor> getProfesorPorRut(String rut) {
        return profesores.stream().filter(p -> p.getRut().equalsIgnoreCase(rut)).findFirst();
    }

    public void crearProfesor() {
        System.out.println("\n--- Crear Nuevo Profesor ---");
        System.out.print("Ingrese RUT del profesor (ej: 12345678-9): ");
        String rut = scanner.nextLine().trim();

        if (getProfesorPorRut(rut).isPresent()) {
            System.out.println("ERROR: Ya existe un profesor con el RUT " + rut + ".");
            return;
        }

        System.out.print("Ingrese nombre del profesor: ");
        String nombre = scanner.nextLine().trim();
        System.out.print("Ingrese departamento del profesor: ");
        String departamento = scanner.nextLine().trim();

        // ID is auto-generated by Profesor constructor if null/empty
        Profesor nuevoProfesor = new Profesor(nombre, rut, departamento, null);
        profesores.add(nuevoProfesor);
        dataManager.guardarProfesores(profesores);
        System.out.println("ÉXITO: Profesor " + nombre + " " + rut + " creado exitosamente.");
    }

    public void listarProfesores() {
        System.out.println("\n--- Listado de Profesores ---");
        if (profesores.isEmpty()) {
            System.out.println("No hay profesores registrados.");
            return;
        }
        profesores.stream()
                .sorted(Comparator.comparing(Profesor::getNombre))
                .forEach(System.out::println);
    }

    public void actualizarProfesor() {
        System.out.println("\n--- Actualizar Profesor ---");
        System.out.print("Ingrese RUT del profesor a actualizar (0 para cancelar): ");
        String rut = scanner.nextLine().trim();
        if (rut.equals("0")) {
            System.out.println("Operación cancelada.");
            return;
        }

        Optional<Profesor> optionalProfesor = getProfesorPorRut(rut);
        if (optionalProfesor.isPresent()) {
            Profesor profesorAActualizar = optionalProfesor.get();
            System.out.println("Profesor actual: " + profesorAActualizar);

            System.out.print("Ingrese nuevo nombre (dejar en blanco para no cambiar): ");
            String nuevoNombre = scanner.nextLine().trim();
            if (!nuevoNombre.isEmpty()) {
                profesorAActualizar.setNombre(nuevoNombre);
            }

            System.out.print("Ingrese nuevo departamento (dejar en blanco para no cambiar): ");
            String nuevoDepartamento = scanner.nextLine().trim();
            if (!nuevoDepartamento.isEmpty()) {
                profesorAActualizar.setDepartamento(nuevoDepartamento);
            }

            dataManager.guardarProfesores(profesores);
            System.out.println("ÉXITO: Profesor actualizado exitosamente.");
        } else {
            System.out.println("ERROR: Profesor con RUT " + rut + " no encontrado.");
        }
    }

    public void eliminarProfesor() {
        System.out.println("\n--- Eliminar Profesor ---");
        System.out.print("Ingrese RUT del profesor a eliminar (0 para cancelar): ");
        String rut = scanner.nextLine().trim();
        if (rut.equals("0")) {
            System.out.println("Operación cancelada.");
            return;
        }

        // IMPORTANT: Before deleting a professor, you might want to check if they have active reservations.
        // This check could be done by AsignacionControlador or a dedicated CheckReserva class.
        // For now, we'll just delete.
        boolean removido = profesores.removeIf(p -> p.getRut().equalsIgnoreCase(rut));

        if (removido) {
            dataManager.guardarProfesores(profesores);
            System.out.println("ÉXITO: Profesor " + rut + " eliminado exitosamente.");
        } else {
            System.out.println("ERROR: Profesor con RUT " + rut + " no encontrado.");
        }
    }
}